services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "{$POSTGRES_DB}"
    ports:
      - "${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: