volumes:
  pgdata:

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: orderflow_app
    restart: always
    depends_on: 
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "${DATABASE_DOCKER_URL}"
      SECRET_KEY: "${SECRET_KEY}"
