"""changed amount type to Decimal for improve operations

Revision ID: d6cd48f142e0
Revises: 9d92f7fd3ec7
Create Date: 2025-08-28 15:15:53.167351

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d6cd48f142e0"
down_revision: Union[str, Sequence[str], None] = "9d92f7fd3ec7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        "movements",
        "amount",
        existing_type=sa.Float(),
        type_=sa.Numeric(precision=12, scale=2),
        existing_nullable=False,
        postgresql_using="amount::numeric",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column(
        "movements",
        "amount",
        existing_type=sa.Numeric(precision=12, scale=2),
        type_=sa.Float(),
        existing_nullable=False,
        postgresql_using="amount::float",
    )
    # ### end Alembic commands ###
